model_path:
  # small: "./model/mistral-7b-instruct-v0.1.Q3_K_M.gguf"
  # large:  "./model/mistral-7b-instruct-v0.1.Q5_K_M.gguf"

  small: "./model/Phi-3.1-mini-128k-instruct-Q5_K_M.gguf"
  large:  "./model/Phi-3.1-mini-128k-instruct-Q5_K_M.gguf"

# model_type: "mistral"
model_type: "ONNX"

# embeddings_path: "BAAI/bge-large-en-v1.5"
embeddings_path: "BAAI/bge-small-en-v1.5"

model_config: {'max_new_tokens': 512, 'temperature': 0, 'context_length': 4096, 'gpu_layers' : 0}

chat_history_path: "./chat_sessions"